//module.exports = greek;

module.exports = {
    // ΐ Π ΰ π β Ϡ κ
    "code1 code2 code3": "0390", // ΐ
    "shift-80": "03A0", // Π,
    "03B0": "ΰ",
    "p": "03C0", // π - 80
    "b": "03D0", // β - 66
    // "03E0",  // Ϡ
    "k": "03F0", //  κ - 75
    // Α Ρ α ρ θ ϡ ρ

    "shift-A": "0391",
    "shift-B": "0392",
    "shift-G": "0393",
    "shift-D": "0394",
    "shift-E": "0395",
    "shift-Z": "0396",
    "shift-H": "0397",
    "shift-U": "0398",
    "shift-I": "0399",
    "shift-K": "039A",
    "shift-L": "039B",
    "shift-M": "039C",
    "shift-N": "039D",
    "shift-X": "039E", // Ksi
    "shift-O": "039F",
    "shift-P": "03A0",

    "shift-S": "03A3",
    "shift-T": "03A4",
    "shift-Y": "03A5",
    "shift-F": "03A6",
    "shift-C": "03A7",
    "shift-": "03A0",
    "shift-J": "03A8",
    "shift-V": "03A9",
    "shift-dialitica-I": "03AA",
    "shift-dialitica-Y": "03AB",

    "A": "03B1",
    "B": "03B2",
    "G": "03B3",
    "D": "03B4",
    "E": "03B5",
    "Z": "03B6",
    "H": "03B7",
    "U": "03B8",
    "I": "03B9",
    "K": "03BA",
    "L": "03BB",
    "M": "03BC",
    "N": "03BD",
    "X": "03BE",
    "O": "03BF",
    "P": "03C0",
    "R": "03C1",
    "W": "03C2",
    "S": "03C3",
    "T": "03C4",
    "Y": "03C5",
    "F": "03C6",
    "C": "03C7",
    "J": "03C8",
    "V": "03C9",

    "shift-dialitica-i": "03CA",
    "shift-dialitica-y": "03CB",

    "shift-psili-a": "1F00",
    "shift-dasia-a": "1F01",
    "shift-psili-varia-a": "1F02",
    "shift-dasia-varia-a": "1F03",
    "shift-psili-oxia-a": "1F04",
    "shift-dasia-oxia-a": "1F05",
    "shift-psili-perispomeni-a": "1F06",
    "shift-dasia-perispomeni-a": "1F07",

    "shift-psili-A": "1F08",
    "shift-dasia-A": "1F09",
    "shift-psili-varia-A": "1F0A",
    "shift-dasia-varia-A": "1F0B",
    "shift-psili-oxia-A": "1F0C",
    "shift-dasia-oxia-A": "1F0D",
    "shift-psili-perispomeni-A": "1F0E",
    "shift-dasia-perispomeni-A": "1F0F",

    "shift-psili-e": "1F10",
    "shift-dasia-e": "1F11",
    "shift-psili-varia-e": "1F12",
    "shift-dasia-varia-e": "1F13",
    "shift-psili-oxia-e": "1F14",
    "shift-dasia-oxia-e": "1F15",

    "shift-psili-E": "1F18",
    "shift-dasia-E": "1F19",
    "shift-psili-varia-E": "1F1A",
    "shift-dasia-varia-E": "1F1B",
    "shift-psili-oxia-E": "1F1C",
    "shift-dasia-oxia-E": "1F1D",

    "shift-psili-h": "1F20",
    "shift-dasia-h": "1F21",
    "shift-psili-varia-h": "1F22",
    "shift-dasia-varia-h": "1F23",
    "shift-psili-oxia-h": "1F24",
    "shift-dasia-oxia-h": "1F25",
    "shift-psili-perispomeni-h": "1F26",
    "shift-dasia-perispomeni-h": "1F27",

    "shift-psili-H": "1F28",
    "shift-dasia-H": "1F29",
    "shift-psili-varia-H": "1F2A",
    "shift-dasia-varia-H": "1F2B",
    "shift-psili-oxia-H": "1F2C",
    "shift-dasia-oxia-H": "1F2D",
    "shift-psili-perispomeni-H": "1F2E",
    "shift-dasia-perispomeni-H": "1F2F",

    "shift-psili-i": "1F30",
    "shift-dasia-i": "1F31",
    "shift-psili-varia-i": "1F32",
    "shift-dasia-varia-i": "1F33",
    "shift-psili-oxia-i": "1F34",
    "shift-dasia-oxia-i": "1F35",
    "shift-psili-perispomeni-i": "1F36",
    "shift-dasia-perispomeni-i": "1F37",

    "shift-psili-I": "1F38",
    "shift-dasia-I": "1F39",
    "shift-psili-varia-I": "1F3A",
    "shift-dasia-varia-I": "1F3B",
    "shift-psili-oxia-I": "1F3C",
    "shift-dasia-oxia-I": "1F3D",
    "shift-psili-perispomeni-I": "1F3E",
    "shift-dasia-perispomeni-I": "1F3F",

    "shift-psili-o": "1F40",
    "shift-dasia-o": "1F41",
    "shift-psili-varia-o": "1F42",
    "shift-dasia-varia-o": "1F43",
    "shift-psili-oxia-o": "1F44",
    "shift-dasia-oxia-o": "1F45",

    "shift-psili-O": "1F38",
    "shift-dasia-O": "1F49",
    "shift-psili-varia-O": "1F4A",
    "shift-dasia-varia-O": "1F4B",
    "shift-psili-oxia-O": "1F4C",
    "shift-dasia-oxia-O": "1F4D",

    "shift-psili-y": "1F50",
    "shift-dasia-y": "1F51",
    "shift-psili-varia-y": "1F52",
    "shift-dasia-varia-y": "1F53",
    "shift-psili-oxia-y": "1F54",
    "shift-dasia-oxia-y": "1F55",
    "shift-psili-perispomeni-y": "1F56",
    "shift-dasia-perispomeni-y": "1F57",

    "shift-psili-Y": "1F58",
    "shift-dasia-Y": "1F59",
    "shift-psili-varia-Y": "1F5A",
    "shift-dasia-varia-Y": "1F5B",
    "shift-psili-oxia-Y": "1F5C",
    "shift-dasia-oxia-Y": "1F5D",
    "shift-psili-perispomeni-Y": "1F5E",
    "shift-dasia-perispomeni-Y": "1F5F",

    "shift-psili-v": "1F60",
    "shift-dasia-v": "1F61",
    "shift-psili-varia-v": "1F62",
    "shift-dasia-varia-v": "1F63",
    "shift-psili-oxia-v": "1F64",
    "shift-dasia-oxia-v": "1F66",
    "shift-psili-perispomeni-v": "1F66",
    "shift-dasia-perispomeni-v": "1F67",

    "shift-psili-V": "1F68",
    "shift-dasia-V": "1F69",
    "shift-psili-varia-V": "1F6A",
    "shift-dasia-varia-V": "1F6B",
    "shift-psili-oxia-V": "1F6C",
    "shift-dasia-oxia-V": "1F6D",
    "shift-psili-perispomeni-V": "1F6E",
    "shift-dasia-perispomeni-V": "1F6F",

    "varia-a": "1F70",
    "oxia-a": "1F71",
    "varia-e": "1F72",
    "oxia-e": "1F73",
    "varia-h": "1F74",
    "oxia-h": "1F75",
    "varia-i": "1F76",
    "oxia-i": "1F77",
    "varia-o": "1F78",
    "oxia-o": "1F79",
    "varia-y": "1F7A",
    "oxia-y": "1F7B",
    "varia-v": "1F7C",
    "oxia-v": "1F7D",

    "shift-psili-ypogegrammeni-a": "1F80",
    "shift-dasia-ypogegrammeni-a": "1F81",
    "shift-psili-varia-ypogegrammeni-a": "1F82",
    "shift-dasia-varia-ypogegrammeni-a": "1F83",
    "shift-psili-oxia-ypogegrammeni-a": "1F84",
    "shift-dasia-oxia-ypogegrammeni-a": "1F85",
    "shift-psili-perispomeni-ypogegrammeni-a": "1F86",
    "shift-dasia-perispomeni-ypogegrammeni-a": "1F87",

    "shift-psili-ypogegrammeni-A": "1F88",
    "shift-dasia-ypogegrammeni-A": "1F89",
    "shift-psili-varia-ypogegrammeni-A": "1F8A",
    "shift-dasia-varia-ypogegrammeni-A": "1F8B",
    "shift-psili-oxia-ypogegrammeni-A": "1F8C",
    "shift-dasia-oxia-ypogegrammeni-A": "1F8D",
    "shift-psili-perispomeni-ypogegrammeni-A": "1F8E",
    "shift-dasia-perispomeni-ypogegrammeni-A": "1F8F",

    "shift-psili-ypogegrammeni-h": "1F90",
    "shift-dasia-ypogegrammeni-h": "1F91",
    "shift-psili-varia-ypogegrammeni-h": "1F92",
    "shift-dasia-varia-ypogegrammeni-h": "1F93",
    "shift-psili-oxia-ypogegrammeni-h": "1F94",
    "shift-dasia-oxia-ypogegrammeni-h": "1F95",
    "shift-psili-perispomeni-ypogegrammeni-h": "1F96",
    "shift-dasia-perispomeni-ypogegrammeni-h": "1F97",

    "shift-psili-ypogegrammeni-H": "1F98",
    "shift-dasia-ypogegrammeni-H": "1F99",
    "shift-psili-varia-ypogegrammeni-H": "1F9A",
    "shift-dasia-varia-ypogegrammeni-H": "1F9B",
    "shift-psili-oxia-ypogegrammeni-H": "1F9C",
    "shift-dasia-oxia-ypogegrammeni-H": "1F9D",
    "shift-psili-perispomeni-ypogegrammeni-H": "1F9E",
    "shift-dasia-perispomeni-ypogegrammeni-H": "1F9F",

    "shift-psili-ypogegrammeni-v": "1FA0",
    "shift-dasia-ypogegrammeni-v": "1FA1",
    "shift-psili-varia-ypogegrammeni-v": "1FA2",
    "shift-dasia-varia-ypogegrammeni-v": "1FA3",
    "shift-psili-oxia-ypogegrammeni-v": "1FA4",
    "shift-dasia-oxia-ypogegrammeni-v": "1FA5",
    "shift-psili-perispomeni-ypogegrammeni-v": "1FA6",
    "shift-dasia-perispomeni-ypogegrammeni-v": "1FA7",

    "shift-psili-ypogegrammeni-V": "1FA8",
    "shift-dasia-ypogegrammeni-V": "1FAA",
    "shift-psili-varia-ypogegrammeni-V": "1FAA",
    "shift-dasia-varia-ypogegrammeni-V": "1FAB",
    "shift-psili-oxia-ypogegrammeni-V": "1FAC",
    "shift-dasia-oxia-ypogegrammeni-V": "1FAD",
    "shift-psili-perispomeni-ypogegrammeni-V": "1FAE",
    "shift-dasia-perispomeni-ypogegrammeni-V": "1FAF",

    // vrachy & macron

    "varia-ypogegrammeni-a": "1FB2",
    "ypogegrammeni-a": "1FB3",
    "oxia-ypogegrammeni-a": "1FB4",

    "perispomeni-a": "1FB6",
    "perispomeni-ypogegrammeni-a": "1FB7",

    "varia-A": "1FBA",
    "oxia-A": "1FBB",
    "ypogegrammeni-C": "1FBC", // prosgegrammeni

    "varia-ypogegrammeni-h": "1FC2",
    "ypogegrammeni-h": "1FC3",
    "oxia-ypogegrammeni-h": "1FC4",

    "perispomeni-h": "1FC6",
    "perispomeni-ypogegrammeni-h": "1FC7",

    "shift-dialitica-varia-i": "1FD2",
    "shift-dialitica-oxia-i": "1FD3",
    "perispomeni-i": "1FD6",
    "shift-dialitica-perispomeni-i": "1FD7",

    "varia-I": "1FDA",
    "oxia-I": "1FDB",

    "shift-dialitica-varia-y": "1FE2",
    "shift-dialitica-oxia-y": "1FE3",

    "shift-psili-r": "1FE4",
    "shift-dasia-r": "1FE5",

    "perispomeni-y": "1FE6",
    "shift-dialitica-perispomeni-y": "1FE7",

    "varia-Y": "1FEA",
    "oxia-Y": "1FEB",

    "shift-dasia-R": "1FEC",

    "varia-ypogegrammeni-v": "1FF2",
    "ypogegrammeni-v": "1FF3",
    "oxia-ypogegrammeni-v": "1FF4",

    "perispomeni-v": "1FF6",
    "perispomeni-ypogegrammeni-v": "1FF7",

    "varia-O": "1FF8",
    "oxia-O": "1FF9",

    "varia-V": "1FFA",
    "oxia-V": "1FFB",

    "ypogegrammeni-V": "1FFC",

    "": "",
    "": "",
    "": "",
    "": "",
    "": ""
}
